namespace Fz.Finanzaseguros.Application.Common.Models.Sarlaft.Response;

public sealed record SarlaftPersonResponse(
  string? Name,
  string? LegalName,
  string? DocumentTypeId,
  string? DocumentTypeName,
  string? IdentificationNumber,
  string? FirstLastName,
  string? SecondLastName,
  string? Dv,
  string? CellPhone,
  string? Email,
  string? PhoneNumber,
  string? Address,
  DateTime? BirthDate,
  string? BirtCityId,
  string? BirtCityName,
  string? NationalityId,
  string? NationalityName,
  string? OtherNationalityId,
  string? OtherNationalityName,
  string? DepartmentId,
  string? DepartmentName,
  string? CityId,
  string? CityName,
  string? CountryId,
  string? Country,
  int? LocationTypeId,
  Guid? CompanyTypeId,
  string? CompanyType,
  SarlaftDocumentIssuanceResponse PersonDocumentIssuance,
  SarlaftEconomicActivityResponse EconomicActivity
);
