using Fz.Identity.Api.Constants;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using Fz.Identity.Api.Database.Entities;

namespace Fz.Identity.Api.Database.Configuration;

public sealed class ClaimConfiguration : IEntityTypeConfiguration<Claim>
{
  public void Configure(EntityTypeBuilder<Claim> builder)
  {
    builder
      .ToTable("Claims", IdentityContextSchemas.Auth);
    builder
      .HasIndex(row => new { row.CalimTypeId, row.Value })
      .IsUnique();
    builder
      .HasOne(row => row.Parent)
      .WithMany(row => row.Children)
      .HasForeignKey(row => row.ParentId)
      .OnDelete(DeleteBehavior.NoAction);
    builder
      .HasOne(row => row.ClaimType)
      .WithMany(row => row.Claims)
      .HasForeignKey(row => row.CalimTypeId);
    builder
      .HasData([
        new Claim { Id = 1, CalimTypeId = 1, Value = "clients:view", Description = "Ver detalle clientes" },
        new Claim { Id = 2, CalimTypeId = 1, Value = "credits:view", Description = "Ver detalle creditos" },
        new Claim { Id = 3, CalimTypeId = 1, Value = "credits:create", Description = "Radicar creditos creditos" },
        new Claim { Id = 4, CalimTypeId = 1, Value = "credits:update", Description = "Actualizar creditos" },
        new Claim { Id = 5, CalimTypeId = 1, Value = "users.view", Description = "Ver usuarios", ActionId = 1, ModuleId = 1 , Order = 1 },
        new Claim { Id = 6, CalimTypeId = 1, Value = "users.create", Description = "Crear usuarios", ActionId = 2, ModuleId = 1, Order = 2 },
        new Claim { Id = 7, CalimTypeId = 1, Value = "users.update", Description = "Actualizar usuarios", ActionId = 3, ModuleId = 1, Order = 3 },
        new Claim { Id = 8, CalimTypeId = 1, Value = "users.delete", Description = "Eliminar usuarios", ActionId = 4, ModuleId = 1, Order = 4 },
        new Claim { Id = 9, CalimTypeId = 1, Value = "users.importExport", Description = "Descargar/Cargar usuarios", ActionId = 5, ModuleId = 1, Order = 5 },
        new Claim { Id = 10, CalimTypeId = 1, Value = "users.review", Description = "Aprobar/Negar usuarios", ActionId = 6, ModuleId = 1, Order = 6 },
        new Claim { Id = 11, CalimTypeId = 1, Value = "roles.view", Description = "Ver roles", ActionId = 1, ModuleId = 2, Order = 1},
        new Claim { Id = 12, CalimTypeId = 1, Value = "roles.create", Description = "Crear roles", ActionId = 2, ModuleId = 2, Order =2 },
        new Claim { Id = 13, CalimTypeId = 1, Value = "roles.update", Description = "Actualizar roles", ActionId = 3, ModuleId = 2 , Order = 3},
        new Claim { Id = 14, CalimTypeId = 1, Value = "roles.delete", Description = "Eliminar roles", ActionId = 4, ModuleId = 2 , Order = 4},
        new Claim { Id = 15, CalimTypeId = 1, Value = "roles.importExport", Description = "Descargar/Cargar roles", ActionId = 5, ModuleId = 2 , Order = 5},
        new Claim { Id = 16, CalimTypeId = 1, Value = "roles.review", Description = "Aprobar/Negar roles", ActionId = 6, ModuleId = 2 , Order = 6},
        new Claim { Id = 17, CalimTypeId = 1, Value = "managements.view", Description = "Ver gestiones", ActionId = 1, ModuleId = 3, Order = 1 },
        new Claim { Id = 18, CalimTypeId = 1, Value = "managements.create", Description = "Crear gestiones", ActionId = 2, ModuleId = 3 , Order = 2},
        new Claim { Id = 19, CalimTypeId = 1, Value = "managements.update", Description = "Actualizar gestiones", ActionId = 3, ModuleId = 3 , Order = 3},
        new Claim { Id = 20, CalimTypeId = 1, Value = "managements.delete", Description = "Eliminar gestiones", ActionId = 4, ModuleId = 3 , Order = 4},
        new Claim { Id = 21, CalimTypeId = 1, Value = "managements.importExport", Description = "Descargar/Cargar gestiones", ActionId = 5, ModuleId = 3 , Order = 5},
        new Claim { Id = 22, CalimTypeId = 1, Value = "managements.review", Description = "Aprobar/Negar gestiones", ActionId = 6, ModuleId = 3 , Order = 6},
        new Claim { Id = 23, CalimTypeId = 1, Value = "requests.view", Description = "Ver solicitudes", ActionId = 1, ModuleId = 4 , Order = 1},
        new Claim { Id = 24, CalimTypeId = 1, Value = "requests.create", Description = "Crear solicitudes", ActionId = 2, ModuleId = 4 , Order = 2},
        new Claim { Id = 25, CalimTypeId = 1, Value = "requests.update", Description = "Actualizar solicitudes", ActionId = 3, ModuleId = 4 , Order = 3},
        new Claim { Id = 26, CalimTypeId = 1, Value = "requests.delete", Description = "Eliminar solicitudes", ActionId = 4, ModuleId = 4 , Order = 4},
        new Claim { Id = 27, CalimTypeId = 1, Value = "requests.importExport", Description = "Descargar/Cargar solicitudes", ActionId = 5, ModuleId = 4 , Order = 5},
        new Claim { Id = 28, CalimTypeId = 1, Value = "requests.review", Description = "Aprobar/Negar solicitudes", ActionId = 6, ModuleId = 4 , Order = 6},
        new Claim { Id = 29, CalimTypeId = 1, Value = "home.main", Description = "Home", ActionId = 1, ModuleId = 5 , Order = 7},
        new Claim { Id = 30, CalimTypeId = 1, Value = "pqrs.main", Description = "Gestión PQRS", ActionId = 1, ModuleId = 6 , Order = 1},
        new Claim { Id = 31, CalimTypeId = 1, Value = "clents.main", Description = "Gestión Clientes", ActionId = 1, ModuleId = 7 , Order = 1},
        new Claim { Id = 32, CalimTypeId = 1, Value = "pqrs.create-vew", Description = "Radicar PQRS - ver", ActionId = 1, ModuleId = 8 , Order = 1},
        new Claim { Id = 33, CalimTypeId = 1, Value = "pqrs.create-create", Description = "Radicar PQRS - crear", ActionId = 2, ModuleId = 8 , Order = 1},
        new Claim { Id = 34, CalimTypeId = 1, Value = "pqrs.create-delete", Description = "Radicar PQRS - eliminar", ActionId = 3, ModuleId = 8 , Order = 1},
        new Claim { Id = 35, CalimTypeId = 1, Value = "pqrs.create-download", Description = "Radicar PQRS - descargar", ActionId = 4, ModuleId = 8 , Order = 1},
        new Claim { Id = 36, CalimTypeId = 1, Value = "pqrs.create-aprove", Description = "Radicar PQRS - aprovar", ActionId = 5, ModuleId = 8 , Order = 1},
        new Claim { Id = 37, CalimTypeId = 1, Value = "client.detail-vew", Description = "Detalle cliente - ver", ActionId = 1, ModuleId = 9 , Order = 1},
        new Claim { Id = 38, CalimTypeId = 1, Value = "client.detail-create", Description = "Detalle cliente - crear", ActionId = 2, ModuleId = 9 , Order = 1},
        new Claim { Id = 39, CalimTypeId = 1, Value = "client.detail-delete", Description = "Detalle cliente - eliminar", ActionId = 3, ModuleId = 9 , Order = 1},
        new Claim { Id = 40, CalimTypeId = 1, Value = "client.detail-download", Description = "Detalle cliente - descargar", ActionId = 4, ModuleId = 9 , Order = 1},
        new Claim { Id = 41, CalimTypeId = 1, Value = "client.detail-aprove", Description = "Detalle cliente - aprovar", ActionId = 5, ModuleId = 9 , Order = 1},
        new Claim { Id = 42, CalimTypeId = 1, Value = "client.bi-vew", Description = "Cliente - información negocio - ver", ActionId = 1, ModuleId = 10 , Order = 1},
        new Claim { Id = 43, CalimTypeId = 1, Value = "client.bi-create", Description = "Cliente - información negocio - crear", ActionId = 2, ModuleId = 10 , Order = 1},
        new Claim { Id = 44, CalimTypeId = 1, Value = "client.bi-delete", Description = "Cliente - información negocio - eliminar", ActionId = 3, ModuleId = 10 , Order = 1},
        new Claim { Id = 45, CalimTypeId = 1, Value = "client.bi-download", Description = "Cliente - información negocio - descargar", ActionId = 4, ModuleId = 10 , Order = 1},
        new Claim { Id = 46, CalimTypeId = 1, Value = "client.bi-aprove", Description = "Cliente - información negocio - aprovar", ActionId = 5, ModuleId = 10 , Order = 1},
        new Claim { Id = 47, CalimTypeId = 1, Value = "client.duh-vew", Description = "Cliente - Histórico actualización de datos - ver", ActionId = 1, ModuleId = 11 , Order = 1},
        new Claim { Id = 48, CalimTypeId = 1, Value = "client.duh-create", Description = "Cliente - Histórico actualización de datos - crear", ActionId = 2, ModuleId = 11 , Order = 1},
        new Claim { Id = 49, CalimTypeId = 1, Value = "client.duh-delete", Description = "Cliente - Histórico actualización de datos - eliminar", ActionId = 3, ModuleId = 11 , Order = 1},
        new Claim { Id = 50, CalimTypeId = 1, Value = "client.duh-download", Description = "Cliente - Histórico actualización de datos - descargar", ActionId = 4, ModuleId = 11 , Order = 1},
        new Claim { Id = 51, CalimTypeId = 1, Value = "client.duh-aprove", Description = "Cliente - Histórico actualización de datos - aprovar", ActionId = 5, ModuleId = 11 , Order = 1},
        new Claim { Id = 52, CalimTypeId = 1, Value = "client.ah-vew", Description = "Cliente - Histórico alfasis - ver", ActionId = 1, ModuleId = 12 , Order = 1},
        new Claim { Id = 53, CalimTypeId = 1, Value = "client.ah-create", Description = "Cliente - Histórico alfasis - crear", ActionId = 2, ModuleId = 12 , Order = 1},
        new Claim { Id = 54, CalimTypeId = 1, Value = "client.ah-delete", Description = "Cliente - Histórico alfasis - eliminar", ActionId = 3, ModuleId = 12 , Order = 1},
        new Claim { Id = 55, CalimTypeId = 1, Value = "client.ah-download", Description = "Cliente - Histórico alfasis - descargar", ActionId = 4, ModuleId = 12 , Order = 1},
        new Claim { Id = 56, CalimTypeId = 1, Value = "client.ah-aprove", Description = "Cliente - Histórico alfasis - aprovar", ActionId = 5, ModuleId = 12 , Order = 1},
        new Claim { Id = 57, CalimTypeId = 1, Value = "client.ci-vew", Description = "Cliente - información de casos - ver", ActionId = 1, ModuleId = 13 , Order = 1},
        new Claim { Id = 58, CalimTypeId = 1, Value = "client.ci-create", Description = "Cliente - información de casos - crear", ActionId = 2, ModuleId = 13 , Order = 1},
        new Claim { Id = 59, CalimTypeId = 1, Value = "client.ci-delete", Description = "Cliente - información de casos - eliminar", ActionId = 3, ModuleId = 13 , Order = 1},
        new Claim { Id = 60, CalimTypeId = 1, Value = "client.ci-download", Description = "Cliente - información de casos - descargar", ActionId = 4, ModuleId = 13 , Order = 1},
        new Claim { Id = 61, CalimTypeId = 1, Value = "client.ci-aprove", Description = "Cliente - información de casos - aprovar", ActionId = 5, ModuleId = 13 , Order = 1},
        new Claim { Id = 62, CalimTypeId = 1, Value = "client.detail-aprove1", Description = "Detalle cliente - aprovar", ActionId = 6, ModuleId = 9 , Order = 1},
        new Claim { Id = 63, CalimTypeId = 1, Value = "client.detail-aprove1", Description = "Detalle cliente - aprovar", ActionId = 6, ModuleId = 9 , Order = 1},
        new Claim { Id = 64, CalimTypeId = 1, Value = "client.bi-aprove1", Description = "Cliente - información negocio - aprovar", ActionId = 6, ModuleId = 10 , Order = 1},
        new Claim { Id = 65, CalimTypeId = 1, Value = "client.duh-aprove1", Description = "Cliente - Histórico actualización de datos - aprovar", ActionId = 6, ModuleId = 11 , Order = 1},
        new Claim { Id = 66, CalimTypeId = 1, Value = "client.ah-aprove1", Description = "Cliente - Histórico alfasis - aprovar", ActionId = 6, ModuleId = 12 , Order = 1},
        new Claim { Id = 67, CalimTypeId = 1, Value = "client.ci-aprove1", Description = "Cliente - información de casos - aprovar", ActionId = 6, ModuleId = 13 , Order = 1},
        new Claim { Id = 68, CalimTypeId = 1, Value = "home.main", Description = "Home", ActionId = 1, ModuleId = 5 , Order = 7},
        new Claim { Id = 69, CalimTypeId = 1, Value = "home.create", Description = "Home", ActionId = 2, ModuleId = 5 , Order = 7},
        new Claim { Id = 70, CalimTypeId = 1, Value = "home.update", Description = "Home", ActionId = 3, ModuleId = 5 , Order = 7},
        new Claim { Id = 71, CalimTypeId = 1, Value = "home.delete", Description = "Home", ActionId = 4, ModuleId = 5 , Order = 7},
        new Claim { Id = 72, CalimTypeId = 1, Value = "home.download", Description = "Home", ActionId = 5, ModuleId = 5 , Order = 7},
        new Claim { Id = 73, CalimTypeId = 1, Value = "home.aprove", Description = "Home", ActionId = 6, ModuleId = 5 , Order = 7},
        new Claim { Id = 74, CalimTypeId = 1, Value = "pqrs.main", Description = "Gestión PQRS", ActionId = 1, ModuleId = 6 , Order = 1},
        new Claim { Id = 75, CalimTypeId = 1, Value = "pqrs.create", Description = "Gestión PQRS", ActionId = 2, ModuleId = 6 , Order = 1},
        new Claim { Id = 76, CalimTypeId = 1, Value = "pqrs.update", Description = "Gestión PQRS", ActionId = 3, ModuleId = 6 , Order = 1},
        new Claim { Id = 77, CalimTypeId = 1, Value = "pqrs.delete", Description = "Gestión PQRS", ActionId = 4, ModuleId = 6 , Order = 1},
        new Claim { Id = 78, CalimTypeId = 1, Value = "pqrs.download", Description = "Gestión PQRS", ActionId = 5, ModuleId = 6 , Order = 1},
        new Claim { Id = 79, CalimTypeId = 1, Value = "pqrs.aprove", Description = "Gestión PQRS", ActionId = 6, ModuleId = 6 , Order = 1},
        new Claim { Id = 80, CalimTypeId = 1, Value = "clents.main", Description = "Gestión Clientes", ActionId = 1, ModuleId = 7 , Order = 1},
        new Claim { Id = 81, CalimTypeId = 1, Value = "clents.create", Description = "Gestión Clientes", ActionId = 2, ModuleId = 7 , Order = 1},
        new Claim { Id = 82, CalimTypeId = 1, Value = "clents.update", Description = "Gestión Clientes", ActionId = 3, ModuleId = 7 , Order = 1},
        new Claim { Id = 83, CalimTypeId = 1, Value = "clents.delete", Description = "Gestión Clientes", ActionId = 4, ModuleId = 7 , Order = 1},
        new Claim { Id = 84, CalimTypeId = 1, Value = "clents.download", Description = "Gestión Clientes", ActionId = 5, ModuleId = 7 , Order = 1},
        new Claim { Id = 85, CalimTypeId = 1, Value = "clents.aprove", Description = "Gestión Clientes", ActionId = 6, ModuleId = 7 , Order = 1},
        new Claim { Id = 86, CalimTypeId = 1, Value = "pqrs.create-aprove1", Description = "Radicar PQRS - aprovar", ActionId = 6, ModuleId = 8 , Order = 1},
        new Claim { Id = 87, CalimTypeId = 1, Value = "cf.pqrs.view", Description = "Gestion PQRS - ver", ActionId = 1, ModuleId = 14, Order = 1},
        new Claim { Id = 88, CalimTypeId = 1, Value = "cf.pqrs.create", Description = "Gestion PQRS - crear", ActionId = 2, ModuleId = 14, Order = 1},
        new Claim { Id = 89, CalimTypeId = 1, Value = "cf.pqrs.update", Description = "Gestion PQRS - editar", ActionId = 3, ModuleId = 14, Order = 1},
        new Claim { Id = 90, CalimTypeId = 1, Value = "cf.pqrs.delete", Description = "Gestion PQRS - eliminar", ActionId = 4, ModuleId = 14, Order = 1},
        new Claim { Id = 91, CalimTypeId = 1, Value = "cf.pqrs.importExport", Description = "Gestion PQRS - descargar/cargar", ActionId = 5, ModuleId = 14, Order = 1},
        new Claim { Id = 92, CalimTypeId = 1, Value = "cf.pqrs.review", Description = "Gestion PQRS - aprobar/negar", ActionId = 6, ModuleId = 14, Order = 1},
        new Claim { Id = 93, CalimTypeId = 1, Value = "cf.clients.view", Description = "Clientes - ver", ActionId = 1, ModuleId = 15, Order = 2},
        new Claim { Id = 94, CalimTypeId = 1, Value = "cf.clients.create", Description = "Clientes - crear", ActionId = 2, ModuleId = 15, Order = 2},
        new Claim { Id = 95, CalimTypeId = 1, Value = "cf.clients.update", Description = "Clientes - editar", ActionId = 3, ModuleId = 15, Order = 2},
        new Claim { Id = 96, CalimTypeId = 1, Value = "cf.clients.delete", Description = "Clientes - eliminar", ActionId = 4, ModuleId = 15, Order = 2},
        new Claim { Id = 97, CalimTypeId = 1, Value = "cf.clients.importExport", Description = "Clientes  - descargar/cargar", ActionId = 5, ModuleId = 15, Order = 2},
        new Claim { Id = 98, CalimTypeId = 1, Value = "cf.clients.review", Description = "Clientes - aprobar/negar", ActionId = 6, ModuleId = 15, Order = 2},
        new Claim { Id = 99, CalimTypeId = 1, Value = "cf.users.view", Description = "Gestion usuarios - ver", ActionId = 1, ModuleId = 16, Order = 3},
        new Claim { Id = 100, CalimTypeId = 1, Value = "cf.users.create", Description = "Gestion usuarios - crear", ActionId = 2, ModuleId = 16, Order = 3},
        new Claim { Id = 101, CalimTypeId = 1, Value = "cf.users.update", Description = "Gestion usuarios - editar", ActionId = 3, ModuleId = 16, Order = 3},
        new Claim { Id = 102, CalimTypeId = 1, Value = "cf.users.delete", Description = "Gestion usuarios - eliminar", ActionId = 4, ModuleId = 16, Order = 3},
        new Claim { Id = 103, CalimTypeId = 1, Value = "cf.users.importExport", Description = "Gestion usuarios - descargar/cargar", ActionId = 5, ModuleId = 16, Order = 3},
        new Claim { Id = 104, CalimTypeId = 1, Value = "cf.users.review", Description = "Gestion usuarios - aprobar/negar", ActionId = 6, ModuleId = 16, Order = 3},
        new Claim { Id = 105, CalimTypeId = 1, Value = "cf.roles.view", Description = "Gestion roles - ver", ActionId = 1, ModuleId = 17, Order = 4},
        new Claim { Id = 106, CalimTypeId = 1, Value = "cf.roles.create", Description = "Gestion roles - crear", ActionId = 2, ModuleId = 17, Order = 4},
        new Claim { Id = 107, CalimTypeId = 1, Value = "cf.roles.update", Description = "Gestion roles - editar", ActionId = 3, ModuleId = 17, Order = 4},
        new Claim { Id = 108, CalimTypeId = 1, Value = "cf.roles.delete", Description = "Gestion roles - eliminar", ActionId = 4, ModuleId = 17, Order = 4},
        new Claim { Id = 109, CalimTypeId = 1, Value = "cf.roles.importExport", Description = "Gestion roles - descargar/cargar", ActionId = 5, ModuleId = 17, Order = 4},
        new Claim { Id = 110, CalimTypeId = 1, Value = "cf.roles.review", Description = "Gestion roles - aprobar/negar", ActionId = 6, ModuleId = 17, Order = 4},
        new Claim { Id = 111, CalimTypeId = 1, Value = "cf.managements-history.view", Description = "Hisotrico gestiones - ver", ActionId = 1, ModuleId = 18, Order = 5},
        new Claim { Id = 112, CalimTypeId = 1, Value = "cf.managements-history.create", Description = "Hisotrico gestiones - crear", ActionId = 1, ModuleId = 18, Order = 5},
        new Claim { Id = 113, CalimTypeId = 1, Value = "cf.managements-history.update", Description = "Hisotrico gestiones - editar", ActionId = 1, ModuleId = 18, Order = 5},
        new Claim { Id = 114, CalimTypeId = 1, Value = "cf.managements-history.delete", Description = "Hisotrico gestiones - eliminar", ActionId = 1, ModuleId = 18, Order = 5},
        new Claim { Id = 115, CalimTypeId = 1, Value = "cf.managements-history.importExport", Description = "Hisotrico gestiones - descargar/cargar", ActionId = 1, ModuleId = 18, Order = 5},
        new Claim { Id = 116, CalimTypeId = 1, Value = "cf.managements-history.review", Description = "Hisotrico gestiones - aprobar/negar", ActionId = 1, ModuleId = 18, Order = 5},
        new Claim { Id = 117, CalimTypeId = 1, Value = "cf.requests.view", Description = "Solicitudes de edicion - ver", ActionId = 1, ModuleId = 19, Order = 6},
        new Claim { Id = 118, CalimTypeId = 1, Value = "cf.requests.create", Description = "Solicitudes de edicion - crear", ActionId = 1, ModuleId = 19, Order = 6},
        new Claim { Id = 119, CalimTypeId = 1, Value = "cf.requests.update", Description = "Solicitudes de edicion - editar", ActionId = 1, ModuleId = 19, Order = 6},
        new Claim { Id = 120, CalimTypeId = 1, Value = "cf.requests.delete", Description = "Solicitudes de edicion - eliminar", ActionId = 1, ModuleId = 19, Order = 6},
        new Claim { Id = 121, CalimTypeId = 1, Value = "cf.requests.importExport", Description = "Solicitudes de edicion - descargar/cargar", ActionId = 1, ModuleId = 19, Order = 6},
        new Claim { Id = 123, CalimTypeId = 1, Value = "cf.requests.review", Description = "Solicitudes de edicion - aprobar/negar", ActionId = 1, ModuleId = 19, Order = 6},
        new Claim { Id = 124, CalimTypeId = 1, Value = "cf.home.view", Description = "Home - ver", ActionId = 1, ModuleId = 20, Order = 7},
        new Claim { Id = 125, CalimTypeId = 1, Value = "cf.home.create", Description = "Home - crear", ActionId = 1, ModuleId = 20, Order = 7},
        new Claim { Id = 126, CalimTypeId = 1, Value = "cf.home.update", Description = "Home - editar", ActionId = 1, ModuleId = 20, Order = 7},
        new Claim { Id = 127, CalimTypeId = 1, Value = "cf.home.delete", Description = "Home - eliminar", ActionId = 1, ModuleId = 20, Order = 7},
        new Claim { Id = 128, CalimTypeId = 1, Value = "cf.home.importExport", Description = "Home - descargar/cargar", ActionId = 1, ModuleId = 20, Order = 7},
        new Claim { Id = 129, CalimTypeId = 1, Value = "cf.home.review", Description = "Home - aprobar/negar", ActionId = 1, ModuleId = 20, Order = 7},
        new Claim { Id = 130, CalimTypeId = 1, Value = "cf.pqrs.file.view", Description = "Radicar PQRS - ver", ActionId = 1, ModuleId = 21, Order = 1},
        new Claim { Id = 131, CalimTypeId = 1, Value = "cf.pqrs.file.create", Description = "Radicar PQRS - crear", ActionId = 1, ModuleId = 21, Order = 1},
        new Claim { Id = 132, CalimTypeId = 1, Value = "cf.pqrs.file.update", Description = "Radicar PQRS - editar", ActionId = 1, ModuleId = 21, Order = 1},
        new Claim { Id = 133, CalimTypeId = 1, Value = "cf.pqrs.file.delete", Description = "Radicar PQRS - eliminar", ActionId = 1, ModuleId = 21, Order = 1},
        new Claim { Id = 134, CalimTypeId = 1, Value = "cf.pqrs.file.importExport", Description = "Radicar PQRS - descargar/cargar", ActionId = 1, ModuleId = 21, Order = 1},
        new Claim { Id = 135, CalimTypeId = 1, Value = "cf.pqrs.file.review", Description = "Radicar PQRS - aprobar/negar", ActionId = 1, ModuleId = 21, Order = 1},
        new Claim { Id = 136, CalimTypeId = 1, Value = "cf.pqrs.management.view", Description = "Gestion PQRS - ver", ActionId = 1, ModuleId = 22, Order = 2},
        new Claim { Id = 137, CalimTypeId = 1, Value = "cf.pqrs.management.create", Description = "Gestion PQRS - crear", ActionId = 1, ModuleId = 22, Order = 2},
        new Claim { Id = 138, CalimTypeId = 1, Value = "cf.pqrs.management.update", Description = "Gestion PQRS - editar", ActionId = 1, ModuleId = 22, Order = 2},
        new Claim { Id = 139, CalimTypeId = 1, Value = "cf.pqrs.management.delete", Description = "Gestion PQRS - eliminar", ActionId = 1, ModuleId = 22, Order = 2},
        new Claim { Id = 140, CalimTypeId = 1, Value = "cf.pqrs.management.importExport", Description = "Gestion PQRS - descargar/cargar", ActionId = 1, ModuleId = 22, Order = 2},
        new Claim { Id = 141, CalimTypeId = 1, Value = "cf.pqrs.management.review", Description = "Gestion PQRS - aprobar/negar", ActionId = 1, ModuleId = 22, Order = 2},
        new Claim { Id = 142, CalimTypeId = 1, Value = "cf.clients.detail.view", Description = "Deatlle Cliente - ver", ActionId = 1, ModuleId = 23, Order = 1},
        new Claim { Id = 143, CalimTypeId = 1, Value = "cf.clients.detail.create", Description = "Deatlle Cliente - crear", ActionId = 1, ModuleId = 23, Order = 1},
        new Claim { Id = 144, CalimTypeId = 1, Value = "cf.clients.detail.update", Description = "Deatlle Cliente - editar", ActionId = 1, ModuleId = 23, Order = 1},
        new Claim { Id = 145, CalimTypeId = 1, Value = "cf.clients.detail.delete", Description = "Deatlle Cliente - eliminar", ActionId = 1, ModuleId = 23, Order = 1},
        new Claim { Id = 146, CalimTypeId = 1, Value = "cf.clients.detail.importExport", Description = "Deatlle Cliente - descargar/cargar", ActionId = 1, ModuleId = 23, Order = 1},
        new Claim { Id = 147, CalimTypeId = 1, Value = "cf.clients.detail.review", Description = "Deatlle Cliente - aprobar/negar", ActionId = 1, ModuleId = 23, Order = 1},
        new Claim { Id = 148, CalimTypeId = 1, Value = "cf.clients.business-info.view", Description = "Informacion negocio - ver", ActionId = 1, ModuleId = 24, Order = 2},
        new Claim { Id = 149, CalimTypeId = 1, Value = "cf.clients.business-info.create", Description = "Informacion negocio - crear", ActionId = 1, ModuleId = 24, Order = 2},
        new Claim { Id = 150, CalimTypeId = 1, Value = "cf.clients.business-info.update", Description = "Informacion negocio - editar", ActionId = 1, ModuleId = 24, Order = 2},
        new Claim { Id = 151, CalimTypeId = 1, Value = "cf.clients.business-info.delete", Description = "Informacion negocio - eliminar", ActionId = 1, ModuleId = 24, Order = 2},
        new Claim { Id = 152, CalimTypeId = 1, Value = "cf.clients.business-info.importExport", Description = "Informacion negocio - descargar/cargar", ActionId = 1, ModuleId = 24, Order = 2},
        new Claim { Id = 153, CalimTypeId = 1, Value = "cf.clients.business-info.review", Description = "Informacion negocio - aprobar/negar", ActionId = 1, ModuleId = 24, Order = 2},
        new Claim { Id = 154, CalimTypeId = 1, Value = "cf.clients.update-history.view", Description = "Historico actualizacion de datos - ver", ActionId = 1, ModuleId = 25, Order = 3},
        new Claim { Id = 155, CalimTypeId = 1, Value = "cf.clients.update-history.create", Description = "Historico actualizacion de datos - crear", ActionId = 1, ModuleId = 25, Order = 3},
        new Claim { Id = 156, CalimTypeId = 1, Value = "cf.clients.update-history.update", Description = "Historico actualizacion de datos - editar", ActionId = 1, ModuleId = 25, Order = 3},
        new Claim { Id = 157, CalimTypeId = 1, Value = "cf.clients.update-history.delete", Description = "Historico actualizacion de datos - eliminar", ActionId = 1, ModuleId = 25, Order = 3},
        new Claim { Id = 158, CalimTypeId = 1, Value = "cf.clients.update-history.importExport", Description = "Historico actualizacion de datos - descargar/cargar", ActionId = 1, ModuleId = 25, Order = 3},
        new Claim { Id = 159, CalimTypeId = 1, Value = "cf.clients.update-history.review", Description = "Historico actualizacion de datos - aprobar/negar", ActionId = 1, ModuleId = 25, Order = 3},
        new Claim { Id = 160, CalimTypeId = 1, Value = "cf.clients.alfasis-history.view", Description = "Historico alfasis - ver", ActionId = 1, ModuleId = 26, Order = 4},
        new Claim { Id = 161, CalimTypeId = 1, Value = "cf.clients.alfasis-history.create", Description = "Historico alfasis - crear", ActionId = 1, ModuleId = 26, Order = 4},
        new Claim { Id = 162, CalimTypeId = 1, Value = "cf.clients.alfasis-history.update", Description = "Historico alfasis - editar", ActionId = 1, ModuleId = 26, Order = 4},
        new Claim { Id = 163, CalimTypeId = 1, Value = "cf.clients.alfasis-history.delete", Description = "Historico alfasis - eliminar", ActionId = 1, ModuleId = 26, Order = 4},
        new Claim { Id = 164, CalimTypeId = 1, Value = "cf.clients.alfasis-history.importExport", Description = "Historico alfasis - descargar/cargar", ActionId = 1, ModuleId = 26, Order = 4},
        new Claim { Id = 165, CalimTypeId = 1, Value = "cf.clients.alfasis-history.review", Description = "Historico alfasis - aprobar/negar", ActionId = 1, ModuleId = 26, Order = 4},
        new Claim { Id = 166, CalimTypeId = 1, Value = "cf.clients.case-info.view", Description = "Infromacion de casos - ver", ActionId = 1, ModuleId = 27, Order = 5},
        new Claim { Id = 167, CalimTypeId = 1, Value = "cf.clients.case-info.create", Description = "Infromacion de casos - crear", ActionId = 1, ModuleId = 27, Order = 5},
        new Claim { Id = 168, CalimTypeId = 1, Value = "cf.clients.case-info.update", Description = "Infromacion de casos - editar", ActionId = 1, ModuleId = 27, Order = 5},
        new Claim { Id = 169, CalimTypeId = 1, Value = "cf.clients.case-info.delete", Description = "Infromacion de casos - eliminar", ActionId = 1, ModuleId = 27, Order = 5},
        new Claim { Id = 170, CalimTypeId = 1, Value = "cf.clients.case-info.importExport", Description = "Infromacion de casos - descargar/cargar", ActionId = 1, ModuleId = 27, Order = 5},
        new Claim { Id = 171, CalimTypeId = 1, Value = "cf.clients.case-info.review", Description = "Infromacion de casos - aprobar/negar", ActionId = 1, ModuleId = 27, Order = 5},
        new Claim { Id = 172, CalimTypeId = 1, Value = "cf.sub-clients.view", Description = "Clientes - ver", ActionId = 1, ModuleId = 28, Order = 6},
        new Claim { Id = 173, CalimTypeId = 1, Value = "cf.sub-clients.create", Description = "Clientes - crear", ActionId = 1, ModuleId = 28, Order = 6},
        new Claim { Id = 174, CalimTypeId = 1, Value = "cf.sub-clients.update", Description = "Clientes - editar", ActionId = 1, ModuleId = 28, Order = 6},
        new Claim { Id = 175, CalimTypeId = 1, Value = "cf.sub-clients.delete", Description = "Clientes - eliminar", ActionId = 1, ModuleId = 28, Order = 6},
        new Claim { Id = 176, CalimTypeId = 1, Value = "cf.sub-clients.importExport", Description = "Clientes - descargar/cargar", ActionId = 1, ModuleId = 28, Order = 6},
        new Claim { Id = 177, CalimTypeId = 1, Value = "cf.sub-clients.review", Description = "Clientes - aprobar/negar", ActionId = 1, ModuleId = 28, Order = 6},
      ]);
  }
}
