using Fz.Identity.Api.Constants;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Route = Fz.Identity.Api.Database.Entities.Route;

namespace Fz.Identity.Api.Database.Configuration;

public sealed class RouteConfiguration : IEntityTypeConfiguration<Route>
{
  public void Configure(EntityTypeBuilder<Route> builder)
  {

    builder.ToTable("Routes", IdentityContextSchemas.Configuration);
    builder.HasIndex(row => new { row.ApplitionId, row.Name, row.Path }).IsUnique();
    builder.HasOne(row => row.Application)
      .WithMany(row => row.Routes)
      .HasForeignKey(row => row.ApplitionId)
      .OnDelete(DeleteBehavior.NoAction);
    builder.HasOne(row => row.Parent)
      .WithMany(row => row.Children)
      .HasForeignKey(row => row.ParentId)
      .OnDelete(DeleteBehavior.NoAction);

    builder
      .HasData([
        new() { Id = 1, ApplitionId = 7, Name = "Tus Solicitudes", Description = "Toda la información sobre el progreso y cualquier actualización relevante de los trámites.", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/your-requests", ExcludeNav = false, Component = "your-requests" },
        new() { Id = 2, ApplitionId = 7, Name = "Inicio", Description = "Inicio", UrlImg = string.Empty, Path = "/", ExcludeNav = true, Component = "home" },
        new() { Id = 3, ApplitionId = 7, Name = "Detalle del cliente", Description = "Detalle e información del cliente.", UrlImg = string.Empty, Path = "/your-requests/request-client-detail/:requestId", ExcludeNav = true, Component = "request-client-detail" },
        new() { Id = 4, ApplitionId = 7, Name = "Radicación de crédito", Description = "Aquí podrás radicar solicitudes y seguir sus avance paso a paso.", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/76c401b9fc50c1d94bd6dbf81b85f679.jfif", Path = "/credit-filing", ExcludeNav = false, Component = "credit-filing" },
        new() { Id = 6, ApplitionId = 7, Name = "Panel Administrativo", Description = "Accede a las herramientas y configuraciones esenciales para gestionar usuarios.", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.webp", Path = "/admin-panel", ExcludeNav = false, Component = "admin-panel" },
        new() { Id = 9, ApplitionId = 7, Name = "Crear nuevo usuario", Description = "Crea nuevos usuarios en el sistema", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.webp", Path = "/admin-panel/create-user", ExcludeNav = true, Component = "admin-user" },
        new() { Id = 11, ApplitionId = 7, Name = "Detalle de usuario", Description = "Edita los usuarios del sistema", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.webp", Path = "/admin-panel/user/:userId", ExcludeNav = true, Component = "admin-user" },
        new() { Id = 13, ApplitionId = 7, Name = "Tus informes", Description = "Consulta y descarga tus informes de manera rápida y sencilla.", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.webp", Path = "/reports", ExcludeNav = false, Component = "reports" },
        new() { Id = 14, ApplitionId = 8, Name = "Externos", Description = "Vista de usuarios externos con cambio de estado.", UrlImg = string.Empty, Path = "/external-user", ExcludeNav = false, Component = "externalUser", Order = 1, ParentId = 87 },
        new() { Id = 15, ApplitionId = 8, Name = "Internos", Description = "Vista de usuarios internos con cambio de estado, regristro y edición.", UrlImg = string.Empty, Path = "/internal-user", ExcludeNav = false, Component = "internalUser", Order = 2, ParentId = 87 },
        new() { Id = 16, ApplitionId = 8, Name = "Gestión documental", Description = string.Empty, UrlImg = string.Empty, Path = string.Empty, ExcludeNav = false, Component = string.Empty, Order = 3 },
        new() { Id = 17, ApplitionId = 8, Name = "Carrusel de imagenes", Description = "Vista gestor de contenido para el carrousel con cambio de estado, orden, registro y detalle.", UrlImg = string.Empty, Path = "/carousel-images", ExcludeNav = false, Component = "CarrouselImages", Order = 1, ParentId = 89 },
        new() { Id = 18, ApplitionId = 8, Name = "Inversionistas", Description = "Vista gestor de contenido para inversionistas con cambio de estado y agregar hijos.", UrlImg = string.Empty, Path = "/investors", ExcludeNav = false, Component = "investors", Order = 2, ParentId = 16 },
        new() { Id = 19, ApplitionId = 8, Name = "Oficinas", Description = "Vista gestor de contenido para oficinas con cambio de estado, registro y edición.", UrlImg = string.Empty, Path = "/offices", ExcludeNav = false, Component = "offices", Order = 1, ParentId = 88 },
        new() { Id = 20, ApplitionId = 8, Name = "Sostenibilidad", Description = "Vista gestor de contenido para sostenibilidad con cambio de estado, registro y edición.", UrlImg = string.Empty, Path = "/sustainability", ExcludeNav = false, Component = "sustainability", Order = 3, ParentId = 16 },
        new() { Id = 21, ApplitionId = 8, Name = "Políticas", Description = "Vista gestor de contenido para polizas con cambio de estado, registro y edición.", UrlImg = string.Empty, Path = "/policies", ExcludeNav = false, Component = "policies", Order = 1, ParentId = 16 },
        new() { Id = 22, ApplitionId = 4, Name = "Inicio", Description = "Inicio", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/", ExcludeNav = true, Component = "home" },
        new() { Id = 23, ApplitionId = 4, Name = "Gestión PQRS", Description = "Gestión PQRS", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/pqrs-management", ExcludeNav = true, Component = "pqrs-management" },
        new() { Id = 24, ApplitionId = 4, Name = "Gestión llamadas", Description = "Gestión llamadas", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/call-management", ExcludeNav = true, Component = "call-management" },
        new() { Id = 25, ApplitionId = 4, Name = "Clientes", Description = "Clientes", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/clients", ExcludeNav = true, Component = "clients" },
        new() { Id = 26, ApplitionId = 4, Name = "Admin Agentes", Description = "Admin Agentes", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/agent-manager", ExcludeNav = true, Component = "agent-manager" },
        new() { Id = 27, ApplitionId = 4, Name = "WhatsApp", Description = "WhatsApp", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/whatsapp", ExcludeNav = true, Component = "whatsapp" },
        new() { Id = 28, ApplitionId = 4, Name = "Admin Comunicaciones", Description = "Admin Comunicaciones", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/communications-manager0", ExcludeNav = true, Component = "communications-manager" },
        new() { Id = 29, ApplitionId = 4, Name = "Histórico", Description = "Histórico", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/historical", ExcludeNav = true, Component = "historical" },
        new() { Id = 30, ApplitionId = 4, Name = "Informes", Description = "Informes", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/reports", ExcludeNav = true, Component = "reports" },
        new() { Id = 31, ApplitionId = 4, Name = "Resumen de caso PQRS", Description = "Resumen de caso PQRS", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/pqrs-management/pqrs-summary/:caseTypeId", ExcludeNav = true, Component = "pqrs-summary" },
        new() { Id = 32, ApplitionId = 4, Name = "Detalle de caso NO.", Description = "Detalle de caso NO.", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/pqrs-management/pqrs-detail/:pqrsId", ExcludeNav = true, Component = "pqrs-management-detail" },
        new() { Id = 33, ApplitionId = 4, Name = "Radicar PQRS", Description = "Radicar PQRS", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/pqrs-management/file-pqrs", ExcludeNav = true, Component = "file-pqrs" },
        new() { Id = 34, ApplitionId = 4, Name = "Detalle de Cliente", Description = "Detalle de Cliente", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/client/client-detail/:clientId", ExcludeNav = true, Component = "client-detail" },
        new() { Id = 40, ApplitionId = 4, Name = "Detalle Agente", Description = "Detalle Agente", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/agent-manager/agent-detail/:agentName", ExcludeNav = true, Component = "agent-detail" },
        new() { Id = 41, ApplitionId = 4, Name = "Calendario", Description = "Calendario", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/calendar", ExcludeNav = true, Component = "calendar" },
        new() { Id = 45, ApplitionId = 4, Name = "Correos", Description = "Correos", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/email", ExcludeNav = true, Component = "email" },
        new() { Id = 46, ApplitionId = 4, Name = "Gestión de usuarios", Description = "Gestión de usuarios", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/user-management", ExcludeNav = false, Component = "user-management", Order = 1 },
        new() { Id = 47, ApplitionId = 4, Name = "Gestión de roles", Description = "Gestión de roles", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/role-management", ExcludeNav = false, Component = "role-management", Order = 2 },
        new() { Id = 48, ApplitionId = 4, Name = "Histórico de gestiones", Description = "Histórico de gestiones", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/history-management", ExcludeNav = false, Component = "history-management", Order = 3 },
        new() { Id = 49, ApplitionId = 4, Name = "Nuevo usuario", Description = "Gestión de usuarios", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/user-management/create-user", ExcludeNav = true, Component = "actions-user" },
        new() { Id = 50, ApplitionId = 4, Name = "Editar usuario", Description = "Gestión de usuarios", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/user-management/edit-user/:id", ExcludeNav = true, Component = "actions-user" },
        new() { Id = 51, ApplitionId = 4, Name = "Detalle usuario", Description = "Gestión de usuarios", UrlImg = "https://www.finanzauto.info/finanzauto.finanzaseguros.api/files/3d8d9f7c0e622acad670eb3530fd6196.jfif", Path = "/user-management/view-user/:id", ExcludeNav = true, Component = "actions-user" },
        new() { Id = 52, ApplitionId = 9, Name = "Inicio", Description = "Inicio", UrlImg = "Home", Path = "/", ExcludeNav = false, Component = "home" },
        new() { Id = 53, ApplitionId = 9, Name = "Gestión de llamadas", Description = "Gestión de llamadas", UrlImg = "Call", Path = "/call_management", ExcludeNav = false, Component = "call-management" },
        new() { Id = 54, ApplitionId = 9, Name = "Informes", Description = "Informes", UrlImg = "Report", Path = "/reports", ExcludeNav = false, Component = "reports" },
        new() { Id = 55, ApplitionId = 9, Name = "Campañas", Description = "Campañas", UrlImg = "Campaign", Path = "/campaigns", ExcludeNav = false, Component = "campaigns" },
        new() { Id = 56, ApplitionId = 9, Name = "Gestión de llamada seleccionada", Description = "Gestión de llamada seleccionada", UrlImg = string.Empty, Path = "/call_management/user_info/:customerId", ExcludeNav = true, Component = "customer-id" },
        new() { Id = 57, ApplitionId = 9, Name = "Editar perfil", Description = "Editar perfil", UrlImg = string.Empty, Path = "/agent/edit_agent/:agentId", ExcludeNav = true, Component = "agent-edit" },
        new() { Id = 58, ApplitionId = 9, Name = "Detalle panel agente", Description = "Detalle panel agente", UrlImg = string.Empty, Path = "/agent/agent_panel/:agentId", ExcludeNav = true, Component = "agent-panel" },
        new() { Id = 59, ApplitionId = 9, Name = "Gestión de llamada seleccionada", Description = "Gestión de llamada seleccionada", UrlImg = string.Empty, Path = "/call_management/detail_call_management/:customerId", ExcludeNav = true, Component = "deatil-call-management" },
        new() { Id = 60, ApplitionId = 9, Name = "asd", Description = "asd", UrlImg = "sdf", Path = "/deatil_call_management/:agentId", ExcludeNav = false, Component = "sdfsdf" },
        new() { Id = 61, ApplitionId = 9, Name = "Colas", Description = "Colas", UrlImg = "Queue", Path = "/queue", ExcludeNav = false, Component = "queue" },
        new() { Id = 62, ApplitionId = 9, Name = "Información del cliente", Description = "Información del cliente", UrlImg = string.Empty, Path = "/call_management/client_information/:identificationNumber", ExcludeNav = true, Component = "client-information" },
        new() { Id = 63, ApplitionId = 3, Name = "Inicio", Description = string.Empty, UrlImg = string.Empty, Path = "/", ExcludeNav = false, Component = "home" },
        new() { Id = 64, ApplitionId = 3, Name = "Indicadores", Description = string.Empty, UrlImg = string.Empty, Path = "/indicators", ExcludeNav = false, Component = "indicators" },
        new() { Id = 65, ApplitionId = 3, Name = "Proveedores", Description = string.Empty, UrlImg = string.Empty, Path = "/providers", ExcludeNav = false, Component = "providers" },
        new() { Id = 66, ApplitionId = 3, Name = "Registro proveedor", Description = string.Empty, UrlImg = string.Empty, Path = "/providers/create-provider", ExcludeNav = true, Component = "create-provider" },
        new() { Id = 67, ApplitionId = 3, Name = "Detalle proveedor", Description = string.Empty, UrlImg = string.Empty, Path = "/providers/:providerId", ExcludeNav = true, Component = "detail-provider" },
        new() { Id = 68, ApplitionId = 3, Name = "Aseguradoras", Description = string.Empty, UrlImg = string.Empty, Path = "/insurers", ExcludeNav = false, Component = "insurers" },
        new() { Id = 69, ApplitionId = 3, Name = "Registro aseguradora", Description = string.Empty, UrlImg = string.Empty, Path = "/insurers/create-insurer", ExcludeNav = true, Component = "create-insurer" },
        new() { Id = 70, ApplitionId = 3, Name = "Aseguradoras", Description = string.Empty, UrlImg = string.Empty, Path = "/insurers/:insurerId", ExcludeNav = true, Component = "detail-insurer" },
        new() { Id = 71, ApplitionId = 3, Name = "Gestiones", Description = string.Empty, UrlImg = string.Empty, Path = "/", ExcludeNav = false, Component = "home" },
        new() { Id = 72, ApplitionId = 4, Name = "Gestión de plantillas", Description = string.Empty, UrlImg = string.Empty, Path = "/template-management", Order = 1, ExcludeNav = true, Component = "TemplateManagement", ParentId = 28 },
        new() { Id = 73, ApplitionId = 4, Name = "Detalle rol", Description = string.Empty, UrlImg = string.Empty, Path = "/role-management/view-rol/:id", ExcludeNav = true, Component = "rol-actions" },
        new() { Id = 74, ApplitionId = 4, Name = "Editar rol", Description = string.Empty, UrlImg = string.Empty, Path = "/role-management/edit-rol/:id", ExcludeNav = true, Component = "rol-actions" },
        new() { Id = 75, ApplitionId = 4, Name = "Crear rol", Description = string.Empty, UrlImg = string.Empty, Path = "/role-management/create-rol", ExcludeNav = true, Component = "rol-actions" },
        new() { Id = 76, ApplitionId = 2, Name = "Mi calendario", Description = "Mi calendario.", UrlImg = string.Empty, Path = "/my-calendar", Order = 0, ExcludeNav = true, Component = "my-calendar" },
        new() { Id = 77, ApplitionId = 2, Name = "Gestión detallada", Description = "Gestión detallada", UrlImg = string.Empty, Path = "/detail-management", Order = 1, ExcludeNav = true, Component = "detail-management" },
        new() { Id = 78, ApplitionId = 2, Name = "Validar de datos", Description = "Validar los datos del cliente", UrlImg = string.Empty, Path = "/validate-customer-info", Order = 2, ExcludeNav = true, Component = "validate-customer-info" },
        new() { Id = 79, ApplitionId = 2, Name = "Solicitud de terceros", Description = "Gestionar las solicitudes de terceros", UrlImg = string.Empty, Path = "/thirdparty-request", Order = 3, ExcludeNav = true, Component = "thirdparty-request" },
        new() { Id = 80, ApplitionId = 2, Name = "Gestión de roles", Description = "Administrar los roles del sistema", UrlImg = string.Empty, Path = "/role-management", Order = 4, ExcludeNav = true, Component = "role-management" },
        new() { Id = 81, ApplitionId = 2, Name = "Historial de cambios", Description = "Visualizar los cambios realizados en el sistema", UrlImg = string.Empty, Path = "/change-history", Order = 5, ExcludeNav = true, Component = "change-history" },
        new() { Id = 82, ApplitionId = 8, Name = "Pólizas de seguros", Description = "Vista gestor de contenido para pólizas de seguros con cambio de estado, registro y edición.", UrlImg = string.Empty, Path = "/insurance-policies", ExcludeNav = false, Component = "insurancePolicies", Order = 4, ParentId = 16 },
        new() { Id = 83, ApplitionId = 4, Name = "Solciitud editar", Description = string.Empty, UrlImg = string.Empty, Path = "/request-editing", ExcludeNav = true, Component = "request-editing" },
        new() { Id = 84, ApplitionId = 4, Name = "Detalle solciitud edición", Description = string.Empty, UrlImg = string.Empty, Path = "/detail-request-editing/:id", ExcludeNav = true, Component = "detail-request-editing" },
        new() { Id = 85, ApplitionId = 11, Name = "Inicio", Description = "Inicio", UrlImg = "http://192.168.50.177:5033/icons/home_atenea_carfiao_icon.png", Path = "/home", ExcludeNav = false, Component = "home" },
        new() { Id = 86, ApplitionId = 11, Name = "Gestion PQRS", Description = "Gestion PQRS", UrlImg = "http://192.168.50.177:5033/icons/pqrs_atenea_carfiao_icon.png", Path = "/pqrs-management", ExcludeNav = false, Component = "pqrs-management" },
        new() { Id = 87, ApplitionId = 8, Name = "Gestión de usuarios", Description = string.Empty, UrlImg = string.Empty, Path = string.Empty, ExcludeNav = false, Component = string.Empty, Order = 1 },
        new() { Id = 88, ApplitionId = 8, Name = "Gestión Información General", Description = string.Empty, UrlImg = string.Empty, Path = string.Empty, ExcludeNav = false, Component = string.Empty, Order = 2 },
        new() { Id = 89, ApplitionId = 8, Name = "Gestión visual", Description = string.Empty, UrlImg = string.Empty, Path = string.Empty, ExcludeNav = false, Component = string.Empty, Order = 4 },
        new() { Id = 90, ApplitionId = 8, Name = "Preguntas frecuentes", Description = "Vista gestor de contenido para preguntas frecuentes con cambio de estado, registro y edición.", UrlImg = string.Empty, Path = "/frequently-questions", ExcludeNav = false, Component = "frequentlyQuestions", Order = 2, ParentId = 88 },
        new() { Id = 91, ApplitionId = 8, Name = "Contenido de tramites", Description = "Vista gestor de contenido para contenido de tramites con cambio de estado, registro y edición.", UrlImg = string.Empty, Path = "/content-procedures", ExcludeNav = false, Component = "contentProcedures", Order = 3, ParentId = 88 },
        new() { Id = 92, ApplitionId = 8, Name = "Modal alertas", Description = "Vista gestor de contenido para el modal de alertas con cambio de estado, orden, registro y detalle.", UrlImg = string.Empty, Path = "/modal-alerts", ExcludeNav = false, Component = "ModalAlerts", Order = 2, ParentId = 89 },
        new() { Id = 93, ApplitionId = 9, Name = "Gestión de usuarios", Description = "Gestión de usuarios", UrlImg = string.Empty, Path = "/user_management", ExcludeNav = false, Component = "user-management", Order = 1 },
        new() { Id = 94, ApplitionId = 9, Name = "Gestión de roles", Description = "Gestión de roles", UrlImg = string.Empty, Path = "/role_management", ExcludeNav = false, Component = "role-management", Order = 2 },
        new() { Id = 95, ApplitionId = 9, Name = "Histórico de gestiones", Description = "Histórico de gestiones", UrlImg = string.Empty, Path = "/management_history", ExcludeNav = false, Component = "management-history", Order = 3 },
        new() { Id = 96, ApplitionId = 11, Name = "Resumen de caso PQRS", Description = "Resumen de caso PQRS", UrlImg = string.Empty, Path = "/pqrs-management/pqrs-summary/:caseTypeId", ExcludeNav = true, Component = "pqrs-summary", Order = 1 },
        new() { Id = 97, ApplitionId = 11, Name = "Detalle de caso NO.", Description = "Detalle de caso NO.", UrlImg = string.Empty, Path = "/pqrs-management/pqrs-detail/:pqrsId", ExcludeNav = true, Component = "pqrs-management-detail", Order = 2 },
        new() { Id = 98, ApplitionId = 4, Name = "Editar detalle de caso NO.", Description = "Editar detalle de caso NO.", UrlImg = string.Empty, Path = "/pqrs-management/edit-pqrs-detail/:pqrsId", ExcludeNav = true, Component = "pqrs-management-edit", Order = 2 },
        new() { Id = 99, ApplitionId = 11, Name = "Radicar PQRS", Description = "Radicar PQRS", UrlImg = string.Empty, Path = "/pqrs-management/file-pqrs", ExcludeNav = true, Component = "file-pqrs" },
        new() { Id = 100, ApplitionId = 9, Name = "Nuevo usuario", Description = "Gestión de usuarios", UrlImg = string.Empty, Path = "/user-management/create-user", ExcludeNav = true, Component = "actions-user" },
        new() { Id = 101, ApplitionId = 9, Name = "Editar usuario", Description = "Gestión de usuarios", UrlImg = string.Empty, Path = "/user-management/edit-user/:id", ExcludeNav = true, Component = "actions-user" },
        new() { Id = 102, ApplitionId = 9, Name = "Detalle usuario", Description = "Gestión de usuarios", UrlImg = string.Empty, Path = "/user-management/view-user/:id", ExcludeNav = true, Component = "actions-user" },
        new() { Id = 103, ApplitionId = 9, Name = "Detalle rol", Description = string.Empty, UrlImg = string.Empty, Path = "/role-management/view-rol/:id", ExcludeNav = true, Component = "rol-actions" },
        new() { Id = 104, ApplitionId = 9, Name = "Editar rol", Description = string.Empty, UrlImg = string.Empty, Path = "/role-management/edit-rol/:id", ExcludeNav = true, Component = "rol-actions" },
        new() { Id = 105, ApplitionId = 9, Name = "Crear rol", Description = string.Empty, UrlImg = string.Empty, Path = "/role-management/create-rol", ExcludeNav = true, Component = "rol-actions" },
        new() { Id = 106, ApplitionId = 3, Name = "Solicitudes de edición", Description = string.Empty, UrlImg = "https://reporteriapbx.finanzauto.com.co/asisya.atenea.dev/icons/edit-requests.svg", Path = "/", ExcludeNav = false, Component = "home" },
        new() { Id = 107, ApplitionId = 3, Name = "Detalle solicitud", Description = string.Empty, UrlImg = string.Empty, Path = "/edit-requests/:requestId", ExcludeNav = true, Component = "request-detail" },
        new() { Id = 108, ApplitionId = 3, Name = "Gestión de usuarios", Description = string.Empty, UrlImg = "https://reporteriapbx.finanzauto.com.co/asisya.atenea.dev/icons/user-management.svg", Path = "/user-management", ExcludeNav = false, Component = "user-management" },
        new() { Id = 109, ApplitionId = 3, Name = "Nuevo usuario", Description = string.Empty, UrlImg = string.Empty, Path = "/user-managment/create-user", ExcludeNav = true, Component = "create-user" },
        new() { Id = 110, ApplitionId = 3, Name = "Detalle del usuario", Description = string.Empty, UrlImg = string.Empty, Path = "/user-managment/detail-user/:userId", ExcludeNav = true, Component = "detail-user" },
        new() { Id = 111, ApplitionId = 3, Name = "Editar usuario", Description = string.Empty, UrlImg = string.Empty, Path = "/user-managment/edit-user/:userId", ExcludeNav = true, Component = "edit-user" },
        new() { Id = 112, ApplitionId = 3, Name = "Gestión de roles", Description = string.Empty, UrlImg = "https://reporteriapbx.finanzauto.com.co/asisya.atenea.dev/icons/role-management.svg", Path = "/role-management", ExcludeNav = false, Component = "role-management" },
        new() { Id = 113, ApplitionId = 3, Name = "Detalle de rol", Description = string.Empty, UrlImg = string.Empty, Path = "/role-management/role-detail/:roleId", ExcludeNav = true, Component = "role-detail" },
        new() { Id = 114, ApplitionId = 3, Name = "Editar rol", Description = string.Empty, UrlImg = string.Empty, Path = "/role-management/edit-role/:roleId", ExcludeNav = true, Component = "edit-role" },
        new() { Id = 115, ApplitionId = 3, Name = "Histórico de gestiones", Description = string.Empty, UrlImg = "https://reporteriapbx.finanzauto.com.co/asisya.atenea.dev/icons/history-management.svg", Path = "/history-management", ExcludeNav = false, Component = "history-management" },
        new() { Id = 116, ApplitionId = 3, Name = "Detalle solicitud", Description = string.Empty, UrlImg = string.Empty, Path = "/history-management/:managementId", ExcludeNav = true, Component = "management-detail" },
        new() { Id = 117, ApplitionId = 4, Name = "Información del negocio", Description = string.Empty, UrlImg = string.Empty, Path = string.Empty, ExcludeNav = true, Component = "GeneralSummary", ParentId = 34 },
        new() { Id = 118, ApplitionId = 4, Name = "Histórico", Description = string.Empty, UrlImg = string.Empty, Path = string.Empty, ExcludeNav = true, Component = "Historic" , ParentId = 34 },
        new() { Id = 119, ApplitionId = 4, Name = "Historial de comunicación", Description = string.Empty, UrlImg = string.Empty, Path = string.Empty, ExcludeNav = true, Component = "CommunicationHistory", ParentId = 34 },
      ]);
  }
}
